#!/bin/sh
#######################################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:

#  Copyright 2018 RDK Management

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################################

if [ -f /etc/device.properties ]
then
    source /etc/device.properties
fi

if [ -e /rdklogger/log_capture_path_atom.sh ]
then
        source /rdklogger/log_capture_path_atom.sh 
else
        LOG_FOLDER="/rdklogs/logs"
        ATOMCONSOLELOGFILE="$LOG_FOLDER/AtomConsolelog.txt.0"
        exec 3>&1 4>&2 >>$ATOMCONSOLELOGFILE 2>&1 
fi


arping -I $PEER_ARPING_INTF $HOST_ARPING_IP -c 3 > /tmp/.arpingresult

arpingSuccess=`cat /tmp/.arpingresult | tail -1 | grep "reply"`
if [ "$arpingSuccess" != "" ]
then
    isSuccess=`echo $arpingSuccess | cut -f2 -d" "`
    if [ "$isSuccess" != "" ]
    then
        if [ $isSuccess -gt 0 ]
        then
            echo "ARPING_FROM_PEER:Success"
        else
            echo "ARPING_FROM_PEER:Failed 0 Reply"
        fi
    else
        echo "ARPING_FROM_PEER:Failed no count"
    fi
else
   echo "ARPING_FROM_PEER:Failed no Reply"
fi

rm -rf /tmp/.arpingresult
