#!/bin/sh
#######################################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:

#  Copyright 2018 RDK Management

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################################

. /etc/device.properties
. /etc/log_timestamp.sh
if [ -f /etc/mount-utils/getConfigFile.sh ];then
     . /etc/mount-utils/getConfigFile.sh
fi

DROPBEAR_PARAMS_1="/tmp/.dropbear/dropcfg1_selfheal"
DROPBEAR_PARAMS_2="/tmp/.dropbear/dropcfg2_selfheal"
if [ ! -d '/tmp/.dropbear' ]; then
   echo_t "wan_ssh.sh: need to create dropbear dir !!! "
   mkdir -p /tmp/.dropbear
fi
if [ ! -f $DROPBEAR_PARAMS_1 ]; then
   echo_t "wan_ssh.sh: need to create dropbear files !!! " 
   getConfigFile $DROPBEAR_PARAMS_1
fi
if [ ! -f $DROPBEAR_PARAMS_2 ]; then
   echo_t "wan_ssh.sh: need to create dropbear files !!! " 
   getConfigFile $DROPBEAR_PARAMS_2
fi
dropbear -r $DROPBEAR_PARAMS_1 -r $DROPBEAR_PARAMS_2 -E -s -p $ATOM_INTERFACE_IP:22 & > /dev/null 2>&1

