#!/bin/sh
######################################################################################
# If not stated otherwise in this file or this component's Licenses.txt file the
# following copyright and licenses apply:

#  Copyright 2020 RDK Management

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################################

MODEL_NUM=`grep MODEL_NUM /etc/device.properties | cut -d "=" -f2`

platform_checks()
{
if [ "$MODEL_NUM" == "DPC3941" ] || [ "$MODEL_NUM" == "DPC3939" ]; then
 DOWNLOAD_PATH="/tmp/plume_dnld/usr/plume"
 WORKING_PATH="/usr/plume"
 
 if [ -z "$(ls -A /usr/plume/)" ]; then
   echo "Work directory empty, copy from download dir"
   if [ ! -z "$(ls -A /tmp/plume_dnld/usr/plume/)" ]; then
    cp -rf /tmp/plume_dnld/usr/plume/* /usr/plume/
   else
    echo "Downloaded dir is empty"
   fi
 else
   echo "Binaries are available in mount dir"
 fi
fi
 
}
if [ $# -eq 0 ]; then
 echo "No arguments passed"
 exit 0
else
 platform_checks
 /usr/plume/scripts/managers.init $1
fi
