#!/bin/sh
#######################################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:

#  Copyright 2018 RDK Management

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################################

if [ "$2" == "" ] ; then
	exit 0;
fi

idx=$1;
pfix=$((idx-1))
if [ -e "/usr/sbin/rdk_wifi_api_test" ] ; then
rdk_wifi_api_test  wifi_setAPKeyPassphrase $pfix $2
else
wifi_api wifi_setAPKeyPassphrase $pfix $2
fi
